#!/bin/bash
# Secure GitHub token input script

echo "🦞 Secure GitHub Token Setup"
echo "================================"
echo ""
echo "🔐 For security, please enter your token directly in terminal"
echo ""
echo "📋 Steps:"
echo "1. Copy your GitHub token (from https://github.com/settings/tokens)"
echo "2. Run this script in your terminal (not in Telegram)"
echo "3. Paste token when prompted - it will be hidden for security"
echo ""
echo "🎯 Terminal Commands:"
echo "cd /home/samsclaw/.openclaw/workspace/blog"
echo "git push https://YOUR_TOKEN@github.com/samsclaw-byte/sam-clawson-journey.git master"
echo ""
echo "📝 Or use the interactive script:"
echo "bash /home/samsclaw/.openclaw/workspace/push_to_github.sh"
echo ""
echo "✅ After pushing, your blog will be at:"
echo "https://samsclaw-byte.github.io/sam-clawson-journey/"
echo ""
echo "🔒 Security Note: Token will be used once and not stored anywhere"